### ISSUE TITLE
Released opossum 1.8.0 with latest changes

### ISSUE THREAD

**Issue by lance** [julekgwa/simplified-hystrixjs#2]
Hi @julekgwa. I ran across your project (very interesting!) and realized you were the one who submitted the PR for opossum that [fixed the `currentTime` Hystrix attribute](https://github.com/bucharest-gold/opossum/commit/e816f4368c14c46976e014d6e7d7fff0901d9c5e). Just wanted to let you know that your commit is in the [latest release 1.8.0](https://github.com/bucharest-gold/opossum/releases/tag/v1.8.0) which I just pushed today.

**Comment by julekgwa** [comment]
@lance Thanks a lot.
